echo ''
echo 'Docker on Debian v0.9.2021.10.09'
echo ''
echo 'Docker on Debian is open source and connects the Docker CLI to Debian Linux VMs running on x86_64 or Arm64 architectures.'
echo ''
echo 'dockerdeb-connect-socket.sh arch:x86_64|arm64'
echo '  Connect the socket to either the x86_64 or arm64 VM'
echo ''
echo 'dockerdeb-connect-tunnels.sh arch:x86_64|arm64 [-p PORT|-p PORT|...]'
echo '  Forward PORT from the host to the VM'
echo ''
echo 'dockerdeb-kill-tunnels.sh [-p PORT|-p PORT|...]'
echo '  Kill port tunneling from host to VM for the given ports'
echo ''
echo 'dockerdeb-kill-socket.sh'
echo '  Disconnects the socket'
echo ''
